global.PARAMS = 
{
    "FORGE_PRICE": [2.5,3,4,4.5,5],
    "TOKEN_NAME": "DKI",
    "WEAPON_ICON_RANGE": [0,39],
    "WEAPON_INCREMENT_FORGE": 5,
    "INCREMENT_FORGES": 1,
    "WEAPON_DPS_DEFAULT": 12
};